### ISSUE TITLE
Arithmetic operations in select query

### ISSUE THREAD

**Issue by Maxim-Inv** [hiimtmac/PSQLKit#6]
Hello,

I try to implement your library in my project and stuck with an issue, this line:

```h2.$price / h1.$price```

generates the error:

```Referencing operator function '/' on 'FloatingPoint' requires that 'ColumnExpression<Double>' conform to 'FloatingPoint'```

How can I embed  arithmetic in select query?

**Comment by Maxim-Inv** [comment]
To avoid this error I've made my custom class:

```swift
public struct PSQLRaw {
	let value: String
	let alias: String
	
	public init(value: String, alias: String) {
		self.value = value
		self.alias = alias
	}
}

extension PSQLRaw: SelectSQLExpression {
	private struct _Select: SQLExpression {
		let value: String
		let alias: String

		func serialize(to serializer: inout SQLSerializer) {
			serializer.write(value)

			serializer.write(" AS ")
			
			serializer.write("\"")
			serializer.write(alias)
			serializer.write("\"")
		}
	}
	
	public var selectSqlExpression: some SQLExpression {
		_Select(value: value, alias: alias)
	}
}
```

it makes possible to use SQL raw string:

```swift
let expression = PSQLRaw(value: "h2.price / h1.price", alias: "value")
```

But I would like to use a key path.

**Comment by hiimtmac** [comment]
I think we will need to implement some sort of expression (similar to `SUM`/`MAX` etc) which off the top of my head will look something like `ArithmeticOperation<T>` which will be similar to the `CompareExpression` (lhs, operator, rhs). Then we can add operator overloads for common math stuff so you can do `p.$price / p.$price` instead of `ArithmeticOpertation(lhs: p.$price, operation: .divide, rhs: p.$price)`. Gimme a bit and ill try and whip something up

**Comment by Maxim-Inv** [comment]
Oh, great! Thank you. I had been looking at the implementation of this class and also thought that it is more suitable, but I have not figured it out completely yet.

**Comment by hiimtmac** [comment]
Please try tag `0.8.0`. I replicated your issue [in a test](https://github.com/hiimtmac/PSQLKit/blob/d91f45a97f33d2f642a7f37307a506d4f2d43e39/Tests/PSQLKitTests/IssueTests.swift#L9). Let me know if this works for you and we can close the issue!

**Comment by Maxim-Inv** [comment]
It works! Thank you. I really like your library, the query described through your library looks almost like a familiar SQL query.
